spring:
  application:
    name: full-project
  security:
    jwt:
      key: abcdefghijk
      expire: 6
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  datasource:
    url: jdbc:mysql://120.26.110.12:49162/dev_project
    hikari:
      username: dev
      password: p@$$w0rd
    driver-class-name: com.mysql.cj.jdbc.Driver




server:
  port: 9090

